export const userData = [
    {"name": "Johnny Lau", 
    "profilepic": "https://upload.wikimedia.org/wikipedia/en/c/c6/Jesse_Pinkman_S5B.png", 
    "availability": true},
    {"name": "Lucy Li", 
    "profilepic": "https://i.pinimg.com/564x/54/c8/8a/54c88ad0f7f90e5fc390a5570de18604.jpg", 
    "availability": false},
    {"name": "Chinenye Oluka", 
    "profilepic": "https://e0.pxfuel.com/wallpapers/860/511/desktop-wallpaper-instagram-profile-aesthetic-profile-pic.jpg", 
    "availability": false},
    {"name": "Karat Wannissorn", 
    "profilepic": "https://i.pinimg.com/550x/ac/11/7f/ac117f5ad61740c4392bedc38e131278.jpg", 
    "availability": true},
    {"name": "Vihangi Perera", 
    "profilepic": "https://e0.pxfuel.com/wallpapers/699/264/desktop-wallpaper-love-lovememes-funny-profile-cute-disney-for-your-mobile-tablet-explore-aesthetic-cartoon-aesthetic-cartoon-cartoon-background-aesthetic.jpg", 
    "availability": true},
    {"name": "Peter Pan", 
    "profilepic": "https://pbs.twimg.com/profile_images/1262867614528749568/pkWGZ6Hm_400x400.jpg", 
    "availability": false},
]
